### ISSUE TITLE
Crash on open table in RebDroid

### ISSUE THREAD

**Issue by Ajtak** [Snakeice/RebDroid#4]
Hi,
i tried your library, but crash on open table. I use newest version of Realm (1.1.0)
stacktrace is:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.storage/com.github.snakeice.realmdroid.DataViewerActivity}: java.lang.NullPointerException
>   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
>   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
>   at android.app.ActivityThread.access$800(ActivityThread.java:151)
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
>   at android.os.Handler.dispatchMessage(Handler.java:110)
>   at android.os.Looper.loop(Looper.java:193)
>   at android.app.ActivityThread.main(ActivityThread.java:5292)
>   at java.lang.reflect.Method.invokeNative(Native Method)
>   at java.lang.reflect.Method.invoke(Method.java:515)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
>   at dalvik.system.NativeStart.main(Native Method)
>                                   Caused by: java.lang.NullPointerException
>   at com.github.snakeice.realmdroid.ViewAdapter.createContent(ViewAdapter.java:76)
>   at com.github.snakeice.realmdroid.ViewAdapter.generateData(ViewAdapter.java:40)
>   at com.github.snakeice.realmdroid.ViewAdapter.<init>(ViewAdapter.java:34)
>   at com.github.snakeice.realmdroid.DataViewerActivity.onCreate(DataViewerActivity.java:44)
>   at android.app.Activity.performCreate(Activity.java:5264)
>   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
>   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
>   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
>   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
>   at android.os.Handler.dispatchMessage(Handler.java:110) 
>   at android.os.Looper.loop(Looper.java:193) 
>   at android.app.ActivityThread.main(ActivityThread.java:5292) 
>   at java.lang.reflect.Method.invokeNative(Native Method) 
>   at java.lang.reflect.Method.invoke(Method.java:515) 
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
>   at dalvik.system.NativeStart.main(Native Method) 

Can you check it? 
Thank you

**Comment by snakeice** [comment]
Hello,thanks for using,  what version of the library are using?

**Comment by Ajtak** [comment]
Hi, i use version from maven repository (v. 1.2)

**Comment by Ajtak** [comment]
I tried new version (v 1.3), but Nullpointer exception is thrown too.

**Comment by snakeice** [comment]
Hum.. I'm at work, so I get home I will check this

**Comment by snakeice** [comment]
Try use new version 1.4
